name: pointycastle
version: 0.11.1
author: The Pointy Castle team
description: A Dart library implementing cryptographic algorithms
homepage: https://github.com/PointyCastle/pointycastle
environment:
  sdk: ">=0.8.10+6 <2.0.0"
#documentation: http://pointycastle.github.io/docs/
dependencies:
  fixnum: ">=0.10.2 <0.11.0"
  quiver_collection: ">=1.0.0 <2.0.0"
  quiver_pattern: ">=1.0.0 <2.0.0"

dev_dependencies:
  benchmark_harness: ">=1.0.4 <2.0.0"
  browser: ">=0.10.0 <0.11.0"
  matcher: ">=0.12.0 <0.13.0"
  test: ">=0.12.7 <0.13.0"

transformers:
- test/pub_serve:
    $include:
      - test/all_tests_web{.*,}.dart
